Document: ecscope
Title: Debian ecscope Manual
Author: <insert document author here>
Abstract: This manual describes what ecscope is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ecscope/ecscope.sgml.gz

Format: postscript
Files: /usr/share/doc/ecscope/ecscope.ps.gz

Format: text
Files: /usr/share/doc/ecscope/ecscope.text.gz

Format: HTML
Index: /usr/share/doc/ecscope/html/index.html
Files: /usr/share/doc/ecscope/html/*.html
